// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_first_steps = "CgkIktH4wf0CEAIQBQ"; // <GPGSID>
        public const string achievement_monsters_arent_that_bad = "CgkIktH4wf0CEAIQDQ"; // <GPGSID>
        public const string achievement_brand_new = "CgkIktH4wf0CEAIQAw"; // <GPGSID>
        public const string achievement_i_hate_monsters = "CgkIktH4wf0CEAIQDw"; // <GPGSID>
        public const string achievement_roadmaster = "CgkIktH4wf0CEAIQBw"; // <GPGSID>
        public const string achievement_1337_d21v32 = "CgkIktH4wf0CEAIQCQ"; // <GPGSID>
        public const string achievement_i_like_powerups = "CgkIktH4wf0CEAIQCA"; // <GPGSID>
        public const string achievement_monster_kill = "CgkIktH4wf0CEAIQEA"; // <GPGSID>
        public const string achievement_powerup_pro = "CgkIktH4wf0CEAIQDA"; // <GPGSID>
        public const string leaderboard_longest_run = "CgkIktH4wf0CEAIQAQ"; // <GPGSID>
        public const string achievement_i_love_powerups = "CgkIktH4wf0CEAIQCw"; // <GPGSID>
        public const string achievement_new_look = "CgkIktH4wf0CEAIQAg"; // <GPGSID>
        public const string achievement_helicopter_boss = "CgkIktH4wf0CEAIQCg"; // <GPGSID>
        public const string achievement_sunday_driver = "CgkIktH4wf0CEAIQBg"; // <GPGSID>
        public const string achievement_level_up = "CgkIktH4wf0CEAIQBA"; // <GPGSID>
        public const string achievement_i_dont_like_monsters = "CgkIktH4wf0CEAIQDg"; // <GPGSID>

}

