// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_first_steps = "CgkIjeOiodcdEAIQDQ"; // <GPGSID>
        public const string achievement_monsters_arent_that_bad = "CgkIjeOiodcdEAIQCA"; // <GPGSID>
        public const string achievement_brand_new = "CgkIjeOiodcdEAIQAw"; // <GPGSID>
        public const string achievement_i_hate_monsters = "CgkIjeOiodcdEAIQCg"; // <GPGSID>
        public const string achievement_roadmaster = "CgkIjeOiodcdEAIQDw"; // <GPGSID>
        public const string achievement_1337_d21v32 = "CgkIjeOiodcdEAIQEA"; // <GPGSID>
        public const string achievement_i_like_powerups = "CgkIjeOiodcdEAIQBQ"; // <GPGSID>
        public const string achievement_monster_kill = "CgkIjeOiodcdEAIQCw"; // <GPGSID>
        public const string achievement_powerup_pro = "CgkIjeOiodcdEAIQBw"; // <GPGSID>
        public const string achievement_i_love_powerups = "CgkIjeOiodcdEAIQBg"; // <GPGSID>
        public const string achievement_new_look = "CgkIjeOiodcdEAIQAg"; // <GPGSID>
        public const string achievement_helicopter_boss = "CgkIjeOiodcdEAIQDA"; // <GPGSID>
        public const string achievement_sunday_driver = "CgkIjeOiodcdEAIQDg"; // <GPGSID>
        public const string achievement_level_up = "CgkIjeOiodcdEAIQBA"; // <GPGSID>
        public const string leaderboard_richest_drivers = "CgkIjeOiodcdEAIQAQ"; // <GPGSID>
        public const string achievement_i_dont_like_monsters = "CgkIjeOiodcdEAIQCQ"; // <GPGSID>

}

